### ISSUE TITLE
Add support for limited use tokens.

### ISSUE THREAD

**Issue by Bubu** [ZerataX/matrix-registration#55]
**Is your feature request related to a problem?**
I'd like to publicly share invite links to my matrix server, but I'd like to put an upper bound to the number of signups that can happen with this particular token.

**Comment by ZerataX** [comment]
yes this is already implemented in #25 
This PR has kind of lost it's initial scope, so even though everything it sets out to do is already working I also tried to implement 
https://www.freedesktop.org/software/systemd/man/systemd.exec.html#LoadCredential=ID:PATH
to more securely supplement secrets, but I'm kinda stuck with that.

I'll see if I can resolve this issue, or try to remove it from this PR for now, since a lot of issues will be fixed by this.
