### ISSUE TITLE
Remote IP not captured correctly

### ISSUE THREAD

**Issue by timmc** [ZerataX/matrix-registration#82]
api.py uses `request.remote_addr` for IP logging when enabled. However, this is incorrect when behind a reverse proxy, even when the proxy attaches a header listing the "real" IP address -- the `remote_addr` is always going to be the proxy's IP address. Instead, the registration code needs to read something from `request.headers`.

As a complicating factor, matrix-registration doesn't actually know if it's behind a proxy. And if it's not, it can't trust even the last element of the X-Forwarded-For header, and should only accept the `remote_addr`.

There are a few possible solutions, but the approach I took was to concatenate the XFF and the remote IP, as seen in this branch: https://github.com/ZerataX/matrix-registration/compare/master...timmc:timmc/xff

```
            ips = ', '.join(request.headers.getlist('X-Forwarded-For') + [request.remote_addr]) \
                if config.config.ip_logging else False
```

...and store the (string) list of IPs instead of a single IP. (Note also the correction to the nginx config. XFF should be chained, not replaced with a single IP.)

**System:**
- OS: Debian 11 Bullseye
- python version: 3.9.2
- matrix registration version: 663cee1fb6a1bd40f60645d8b25480ac3994963c

**Comment by xelantro** [comment]
Is this testet / merge ready?

**Comment by timmc** [comment]
Depends if you think the change is acceptable -- it would switch from storing a single IP to a list of IPs, which may or may not be something people want. (If that approach is acceptable, I'm happy to submit a PR.)

**Comment by xelantro** [comment]
First of all, I think it a good change. As long as it stays a single string so we dont have to alter the database structure.
Regarding your code (correct me if im wrong, because im not that fluent with flask and shit)
- the code in the readme is the one for the nginx reverse proxy so [$remote_addr](https://nginx.org/en/docs/http/ngx_http_core_module.html#var_remote_addr) should be the clients address? (as long as its the only layer of proxy -> cloudflare, matrix-docker-ansible project), but many ppl use systems with multipls layers of reverse proxys so it'd be still good
- [the nginx website claims](https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/) that the $proxy_add_x_forwarded_for appends the current $remote_addr to the incoming X-Forwarded-For header, so using the header in your phython should be enough and you shouldn't need to append request.remote_addr again
- have you testet that it still works with the old nginx config (backwards comp) and without a reverse proxy?

**Comment by timmc** [comment]
OK, I can work it up as a PR, maybe even with unit tests. :-) I'm not particularly familiar with Flask either.

I can also try testing it manually with different configurations.

**Comment by xelantro** [comment]
Btw: so just that you are aware and to link it: #83 
request.remote_addr was removed and changed to request.get_remote_address
So if my second statement is incorrect and you do need to append it another time, pls swap it

**Comment by xelantro** [comment]
What I just noticed reading [this](https://github.com/ZerataX/matrix-registration/pull/83/files#diff-91991e920961fa71dfc1f680fd9cb1b38538726523f92decdbb0c74cb0bdd359R60) again:
Could it have been that we've been ratelimiting the request from the proxy itself (if present) so for all users (maybe @SapuSeven knows), and whether integrating the header change in the limiter would be possible

**Comment by xelantro** [comment]
@timmc can you open the pr as draft now so we can move the discussion there?

**Comment by SapuSeven** [comment]
> What I just noticed reading [this](https://github.com/ZerataX/matrix-registration/pull/83/files#diff-91991e920961fa71dfc1f680fd9cb1b38538726523f92decdbb0c74cb0bdd359R60) again: Could it have been that we've been ratelimiting the request from the proxy itself (if present) so for all users (maybe @SapuSeven knows), and whether integrating the header change in the limiter would be possible

I have to say that I don't really know how exactly rate limiting works, I just looked at the code changes of the remote repository and noticed that `get_ipaddr` seems to have been replaced with `get_remote_address`.
Sorry for not testing this properly.
